// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID      int    `json:"id"`
	Poster  *User  `json:"poster"`
	Content string `json:"content"`
}

type NewMessage struct {
	PosterID string `json:"posterId"`
	Content  string `json:"content"`
}

type NewUser struct {
	Name string `json:"name"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
